-- Create the sequence first
CREATE SEQUENCE IF NOT EXISTS address_seq START WITH 1 INCREMENT BY 50;

-- Use the sequence for the ID field
CREATE TABLE address (
    id BIGINT PRIMARY KEY,
    street VARCHAR(255),
    city VARCHAR(255)
);

CREATE TABLE client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    address_id BIGINT,
    CONSTRAINT fk_client_address FOREIGN KEY (address_id) REFERENCES address(id)
);

CREATE TABLE client_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product VARCHAR(255),
    client_id BIGINT,
    CONSTRAINT fk_order_client FOREIGN KEY (client_id) REFERENCES client(id)
);
